name: CI tests

on: [workflow_dispatch, push, pull_request]

env:
  DB_ENDPOINT: 'tcp://127.0.0.1:8529'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0]
        arangodb: [3.6.0, 3.6.*, latest]
    name:  Quality checks PHP ${{ matrix.php }} / ArangoDB ${{ matrix.arangodb }}

    services:
      arangodb:
        image: arangodb:${{ matrix.arangodb }}
        ports:
          - 8529:8529
        env:
          ARANGO_NO_AUTH: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}-php-${{ matrix.php }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction

      - name: Run all QA tests
        if: ${{ always() }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/bin/qa.sh"
          "${GITHUB_WORKSPACE}/bin/qa.sh"
        env:
          ARANGODB_VERSION: ${{ matrix.arangodb }}