name: Quality Assurance

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1]
    name:  Quality checks P${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}-php-${{ matrix.php }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction

      - name: Run all QA tests
        if: ${{ always() }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/bin/qa.sh"
          "${GITHUB_WORKSPACE}/bin/qa.sh"
